fix: sec scan  (#93)
Co-authored-by: madara-robot <246592117+madara-robot@users.noreply.github.com>

diff --git a/.github/workflows/security-checks.yml b/.github/workflows/security-checks.yml
--- a/.github/workflows/security-checks.yml
+++ b/.github/workflows/security-checks.yml
@@ -35,3 +35,19 @@ jobs:
         uses: ./.github/workflows/jobs/next-application-security-check
         with:
           service-name: ${{ matrix.service-name }}
+
+  # final job that waits for all security checks
+  security-checks-summary:
+    name: Security checks summary
+    runs-on: ubuntu-latest
+    needs: [ security-scan-nest, security-scan-next ]
+    if: always()
+    steps:
+      - name: Check all security scans status
+        run: |
+          if [ "${{ needs.security-scan-nest.result }}" != "success" ] || [ "${{ needs.security-scan-next.result }}" != "success" ]; then
+            echo "Some security checks failed"
+            exit 1
+          else
+            echo "All security checks passed"
+          fi
